version: "3.1"

services:
  db:
    hostname: mongo
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  api:
    container_name: Efimob
    build:
      context: ./central-system-api
    ports:
      - 8001:8000
    depends_on:
      - db

  cliente:
    container_name: cliente
    build:
      context: ./central-system-for-web
    ports:
      - 3001:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./central-system-for-web:/app
      - ./central-system-for-web/app/node_modules
    depends_on:
      - db
      - api
